<?php

namespace CAF\TestBundle\Repository;

/**
 * MenuPlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuPlatRepository extends \Doctrine\ORM\EntityRepository
{
}
