<?php

namespace CAF\TestBundle\Repository;

/**
 * platRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class platRepository extends \Doctrine\ORM\EntityRepository
{
}
