<?php

namespace CAF\TestBundle\Repository;

/**
 * PlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatRepository extends \Doctrine\ORM\EntityRepository
{
     public function myFindAll() {
        return $this
                        ->createQueryBuilder('a')
        ;
    }
}
