<?php

namespace CAF\CantineBundle\Repository;

/**
 * MenusPlatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenusPlatsRepository extends \Doctrine\ORM\EntityRepository
{
}
