<?php

namespace CAF\CantineBundle\Repository;

/**
 * MenusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenusRepository extends \Doctrine\ORM\EntityRepository
{
}
