<?php

namespace CAF\CantineBundle\Repository;

/**
 * RepasPlatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepasPlatsRepository extends \Doctrine\ORM\EntityRepository
{
}
