<?php

namespace CAF\CantineBundle\Repository;

/**
 * TypePlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePlatRepository extends \Doctrine\ORM\EntityRepository
{
    public function tousTypesPlats() {
        return $this
            ->createQueryBuilder('a')
            ->where('a.id < :var')
            ->setParameter('var', 5) 
        ;
    }
}
