c_af_test:
    resource: "@CAFTestBundle/Resources/config/routing.yml"
    prefix:   /test

caf_popote:
    resource: "@CAFPopoteBundle/Resources/config/routing.yml"
    prefix:   /popote

#caf_cantine:
#    resource: "@CAFCantineBundle/Resources/config/routing.yml"
#    prefix:   /cantine