caf_home:
    path:     /
    defaults: { _controller: CAFPopoteBundle:Menu:index }
    
caf_popote:
    resource: "@CAFPopoteBundle/Resources/config/routing.yml"
    prefix:   /popote

login:
    pattern:   /login
    defaults:  { _controller: CAFUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

