# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        CAF\UserBundle\Entity\User: plaintext
        
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_USER, ROLE_CAF]
        ROLE_SUPER_ADMIN: [ROLE_AUTEUR, ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: fos_user.user_provider.username
#            entity:
#                class:    CAF\UserBundle\Entity\User
#                property: username
    
        app_users:
            ldap:
                service: ldap
                base_dn: dc=cafbayonne,dc=cnaf
                search_dn: administrateur@CAFBAYONNE.CNAF
                search_password: TURBOD
                filter: (sAMAccountName={username})
                default_roles: ROLE_CAF
           
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path:            /menu
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                key:        %secret% 
                
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
        ldap:
            pattern:   ^/
            anonymous: true
            provider:  app_users
            form_login_ldap:
                login_path: login
                check_path: login_check
                # ...
                service: ldap
                dn_string: 'sAMAccountName={userPrincipalName},dc=cafbayonne,dc=cnaf'
            
            
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/admin, ip: 127.0.0.1, requires_channel: https }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_CAF }