# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    
    form_authenticator:
          class: CAF\PopoteBundle\Security\FormAuthenticator
          arguments: ["@router"]
    
    ldap:
        class: Symfony\Component\Ldap\LdapClient
        arguments: [ "SDC1A641.cafbayonne.cnaf" ]
