caf_test_homepage:
    path:     /
    defaults: { _controller: CAFPopoteBundle:Menu:index }

test_plat_index:
    path:     /plat
    defaults: { _controller: CAFTestBundle:Plat:index }
    
test_plat_add:
    path:     /plat/add
    defaults: { _controller: CAFTestBundle:Plat:add }
    
test_menu_index:
    path:     /menu
    defaults: { _controller: CAFTestBundle:Menu:index }
    
test_menu_add:
    path:     /menu/add
    defaults: { _controller: CAFTestBundle:Menu:add }
    

test_repa_add:
    path:     /repa/add
    defaults: { _controller: CAFTestBundle:Repa:addRepa }
    
test_repa_index:
    path:     /repa
    defaults: { _controller: CAFTestBundle:Repa:index }
