popote_plat_index:
    path:      /admin/plat
    defaults: { _controller: CAFPopoteBundle:Plat:index}
        
popote_plat_view:
    path:      /admin/plat/{id}
    defaults: { _controller: CAFPopoteBundle:Plat:view}
    requirements:
        id:   \d{1,4}
        
popote_plat_edit:
    path:      /admin/plat/edit/{id}
    defaults: { _controller: CAFPopoteBundle:Plat:edit}
    requirements:
        id:   \d{1,4}
        
popote_plat_delete:
    path:      /admin/plat/delete/{id}
    defaults: { _controller: CAFPopoteBundle:Plat:delete}
    requirements:
        id:   \d{1,4}

popote_plat_add:
    path:      /admin/plat/add
    defaults: { _controller: CAFPopoteBundle:Plat:add}

popote_plat_ajout:
    path:      /admin/plat/ajout/{type}/{libelle}/{porc}
    defaults: { _controller: CAFPopoteBundle:Plat:ajout, porc: 1} 
    requirements:
        type:   \d{1}
        porc:   0|1
        
popote_typeplat_index:
    path:      /admin/typeplat
    defaults: { _controller: CAFPopoteBundle:TypePlat:index}

popote_typeplat_view:
    path:      /admin/typeplat/{id}
    defaults: { _controller: CAFPopoteBundle:TypePlat:view}
    requirements:
        id:   \d{1,4}
        
popote_typeplat_add:
    path:      /admin/typeplat/add
    defaults: { _controller: CAFPopoteBundle:TypePlat:add}       

popote_typeplat_edit:
    path:      /admin/typeplat/edit/{id}
    defaults: { _controller: CAFPopoteBundle:TypePlat:edit} 
    requirements:
        id:   \d{1,4}   
        
popote_typeplat_delete:
    path:      /admin/typeplat/del/{id}
    defaults: { _controller: CAFPopoteBundle:TypePlat:delete} 
    requirements:
        id:   \d{1,4}   
        
popote_repa_index:
    path:      /repa
    defaults: { _controller: CAFPopoteBundle:Repa:index}
    
popote_repa_view:
    path:      /repa/{id}
    defaults: { _controller: CAFPopoteBundle:Repa:view}
    requirements:
        id:   \d{1,4}
        
popote_repa_add:
    path:      /repa/add/{idMenu}
    defaults: { _controller: CAFPopoteBundle:Repa:add }
    requirements:
        idMenu:   \d{1,4}
        
popote_repa_edit:
    path:      /repa/edit/{id}
    defaults: { _controller: CAFPopoteBundle:Repa:edit}
    requirements:
        id:   \d{1,4}

popote_repa_delete:
    path:      /repa/del/{id}
    defaults: { _controller: CAFPopoteBundle:Repa:delete}
    requirements:
        id:   \d{1,4}

popote_menu_index:
    path:      /menu
    defaults: { _controller: CAFPopoteBundle:Menu:index}

popote_menu_view:
    path:      /menu/{id}
    defaults: { _controller: CAFPopoteBundle:Menu:view}
    requirements:
        id:   \d{1,4}
    
popote_menu_add:
    path:      /admin/menu/add
    defaults: { _controller: CAFPopoteBundle:Menu:add}
    
popote_menu_edit:
    path:      /admin/menu/edit/{id}
    defaults: { _controller: CAFPopoteBundle:Menu:edit}
    requirements:
        id:   \d{1,4}

popote_menu_delete:
    path:      /admin/menu/del/{id}
    defaults: { _controller: CAFPopoteBundle:Menu:delete}
    requirements:
        id:   \d{1,4}
