<?php

namespace CAF\PopoteBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function mFindAll() {
       return $this
        ->createQueryBuilder('a')
        ;
    }
    
    public function findPlats($id) {
        return $this
                        ->createQueryBuilder('a')
                        ->leftJoin('a.mp', 'mp')
                        ->addSelect('mp')
                        ->where('a.id = :id')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->getOneOrNullResult()
        ;
    }
    
     public function findMenuPlats($id) {
        return $this
                        ->createQueryBuilder('a')
                        ->leftJoin('a.mp', 'mp')
                        ->addSelect('mp.plat')
                        ->where('a.id = :id')
                        ->setParameter('id', $id)
                        
        ;
    }
}
