<?php

namespace CAF\PopoteBundle\Repository;

/**
 * RepaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepaRepository extends \Doctrine\ORM\EntityRepository
{
}
