<?php

namespace CAF\PopoteBundle\Repository;

/**
 * RepaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepaRepository extends \Doctrine\ORM\EntityRepository {

    public function myFindId($id) {
        return $this
                        ->createQueryBuilder('a')
                        ->leftJoin('a.rp', 'rp')
                        ->addSelect('rp')
                        ->where('a.id = :id')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->getOneOrNullResult()
        ;
    }

}
