<?php

namespace CAF\PopoteBundle\Repository;

/**
 * TypePlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePlatRepository extends \Doctrine\ORM\EntityRepository
{
    public function allTypePlat() {
        return $this
            ->createQueryBuilder('a')
        ;
    }
}
