caf_cantine_home:
    path:      /
    defaults: { _controller: CAFCantineBundle:Menus:index }

caf_plats_view:
    path:      /plats/{id}
    defaults: { _controller: CAFCantineBundle:Plats:view}
    requirements:
        id:   \d{1,2}
        
caf_plats_edit:
    path:      /plats/edit/{id}
    defaults: { _controller: CAFCantineBundle:Plats:edit}
    requirements:
        id:   \d{1,2}
        
caf_plats_delete:
    path:      /plats/delete/{id}
    defaults: { _controller: CAFCantineBundle:Plats:delete}
    requirements:
        id:   \d{1,2}
        
caf_plats_add:
    path:      /plats/add/{type}/{libelle}/{porc}
    defaults: { _controller: CAFCantineBundle:Plats:add, porc: 1} 
    requirements:
        type:   \d{1}
        porc:   0|1
        
caf_repas_view:
    path:      /repas/{id}
    defaults: { _controller: CAFCantineBundle:Repas:view}
    requirements:
        id:   \d{1,4}
        
caf_repas_add:
    path:      /repas/add
    defaults: { _controller: CAFCantineBundle:Repas:add }


    
