caf_cantine_home:
    path:      /
    defaults: { _controller: CAFCantineBundle:Cantine:menu }

caf_plats_view:
    path:      /plats/
    defaults: { _controller: CAFCantineBundle:Plats:view}
        
caf_plats_edit:
    path:      /plats/edit/{id}
    defaults: { _controller: CAFCantineBundle:Plats:edit}
    requirements:
        id:   \d{1,4}
        
caf_plats_delete:
    path:      /plats/delete/{id}
    defaults: { _controller: CAFCantineBundle:Plats:delete}
    requirements:
        id:   \d{1,4}

caf_plats_add:
    path:      /plats/add/
    defaults: { _controller: CAFCantineBundle:Plats:add}

caf_plats_ajout:
    path:      /plats/ajout/{type}/{libelle}/{porc}
    defaults: { _controller: CAFCantineBundle:Plats:ajout, porc: 1} 
    requirements:
        type:   \d{1}
        porc:   0|1
        
caf_typeplats_view:
    path:      /typeplat/
    defaults: { _controller: CAFCantineBundle:TypePlats:view}

caf_typeplats_add:
    path:      /typeplat/add/
    defaults: { _controller: CAFCantineBundle:TypePlats:add}       

caf_typeplats_edit:
    path:      /typeplat/edit/{id}
    defaults: { _controller: CAFCantineBundle:TypePlats:edit} 
    requirements:
        id:   \d{1,4}   
        
caf_typeplats_delete:
    path:      /typeplat/del/{id}
    defaults: { _controller: CAFCantineBundle:TypePlats:delete} 
    requirements:
        id:   \d{1,4}   
        
caf_repas_view:
    path:      /repas/
    defaults: { _controller: CAFCantineBundle:Repas:view}
        
caf_repas_add:
    path:      /repas/add/
    defaults: { _controller: CAFCantineBundle:Repas:add }

caf_menus_view:
    path:      /menus/
    defaults: { _controller: CAFCantineBundle:Menus:view}
    
caf_menus_add:
    path:      /menus/add/
    defaults: { _controller: CAFCantineBundle:Menus:add}
