caf_cantine_home:
    path:      /
    defaults: { _controller: CAFCantineBundle:Cantine:menu }

caf_plat_index:
    path:      /plat
    defaults: { _controller: CAFCantineBundle:Plat:index}
        
caf_plat_view:
    path:      /plat/view/{id}
    defaults: { _controller: CAFCantineBundle:Plat:view}
    requirements:
        id:   \d{1,4}
        
caf_plat_edit:
    path:      /plat/edit/{id}
    defaults: { _controller: CAFCantineBundle:Plat:edit}
    requirements:
        id:   \d{1,4}
        
caf_plat_delete:
    path:      /plat/delete/{id}
    defaults: { _controller: CAFCantineBundle:Plat:delete}
    requirements:
        id:   \d{1,4}

caf_plat_add:
    path:      /plat/add
    defaults: { _controller: CAFCantineBundle:Plat:add}

caf_plat_ajout:
    path:      /plat/ajout/{type}/{libelle}/{porc}
    defaults: { _controller: CAFCantineBundle:Plat:ajout, porc: 1} 
    requirements:
        type:   \d{1}
        porc:   0|1
        
caf_typeplat_index:
    path:      /typeplat
    defaults: { _controller: CAFCantineBundle:Typeplat:index}

caf_typeplat_view:
    path:      /typeplat/{id}
    defaults: { _controller: CAFCantineBundle:Typeplat:view}
    requirements:
        id:   \d{1,4}
        
caf_typeplat_add:
    path:      /typeplat/add
    defaults: { _controller: CAFCantineBundle:Typeplat:add}       

caf_typeplat_edit:
    path:      /typeplat/edit/{id}
    defaults: { _controller: CAFCantineBundle:Typeplat:edit} 
    requirements:
        id:   \d{1,4}   
        
caf_typeplat_delete:
    path:      /typeplat/del/{id}
    defaults: { _controller: CAFCantineBundle:Typeplat:delete} 
    requirements:
        id:   \d{1,4}   
       
caf_repas_index:
    path:      /repas
    defaults: { _controller: CAFCantineBundle:Repas:index}
      
caf_repas_view:
    path:      /repas/view/{id}
    defaults: { _controller: CAFCantineBundle:Repas:view}
    requirements:
       id:   \d{1,4}
       
caf_repas_add:
    path:      /repas/add
    defaults: { _controller: CAFCantineBundle:Repas:add }
    
caf_menus_index:
    path:      /menus
    defaults: { _controller: CAFCantineBundle:Menus:index}
    
caf_menus_view:
    path:      /menus/{id}
    defaults: { _controller: CAFCantineBundle:Menus:view}
    requirements:
        id:   \d{1,4}
        
caf_menus_add:
    path:      /menus/add
    defaults: { _controller: CAFCantineBundle:Menus:add}
    
caf_menus_edit:
    path:      /menus/edit/{id}
    defaults: { _controller: CAFCantineBundle:Menus:edit}
    requirements:
        id:   \d{1,4}

caf_menus_delete:
    path:      /menus/del/{id}
    defaults: { _controller: CAFCantineBundle:Menus:delete}
    requirements:
        id:   \d{1,4}